version: "2"

vars:
  PREFIX: morsby
  SUFFIX:
    sh: perl -pe 'binmode(STDIN, ":bytes"); tr/a-z0-9//dc;' < /dev/urandom | head -c 32

tasks:
  verify: # task verify
    cmds:
      - ./scripts/functions.sh verify_all _ {{.SUFFIX}}

  build: # task build FUNC=golang-mod
    dir: ./template/{{.FUNC}}
    cmds:
      - docker build -t {{.FUNC}} .

  run: # task run FUNC=golang-mod
    cmds:
      - ./scripts/functions.sh build_template {{.FUNC}} {{.SUFFIX}}
      - echo {{.FUNC}}-{{.SUFFIX}}
      - docker run -d -p 8080:8080 {{.FUNC}}-{{.SUFFIX}}:latest

  debug: # task debug FUNC=golang-mod
    cmds:
      - ./scripts/functions.sh build_template {{.FUNC}} {{.SUFFIX}}
      - echo {{.FUNC}}-{{.SUFFIX}}
      - docker run --rm --name debug-func-{{.SUFFIX}} -p 8081:8080
        {{.FUNC}}-{{.SUFFIX}}:latest
      - docker exec -it debug-func-{{.SUFFIX}}
    ignore_error: true

  clean:
    cmds:
      - rm -rf ./build
